/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-models.html
 */

/// <reference path="project-model.d.ts" />
/// <reference path="request-model.d.ts" />
/// <reference path="url-history-model.d.ts" />
/// <reference path="websocket-url-history-model.d.ts" />
/// <reference path="rest-api-model.d.ts" />
/// <reference path="host-rules-model.d.ts" />
/// <reference path="variables-model.d.ts" />
/// <reference path="auth-data-model.d.ts" />
/// <reference path="url-indexer.d.ts" />

