/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   base-model.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../uuid-generator/uuid-generator.d.ts" />
/// <reference path="../events-target-behavior/events-target-behavior.d.ts" />

/**
 * A base class for all models.
 */
declare class ArcBaseModel {

  /**
   * Note, the element does not include PouchDB to the document!
   */
  readonly db: PouchDB|null;
  readonly uuid: any;
  disconnectedCallback(): void;
  _attachListeners(node: any): void;
  _detachListeners(node: any): void;

  /**
   * Reads an entry from the datastore.
   *
   * @param id The ID of the datastore entry.
   * @param rev Specific revision to read. Defaults to latest revision.
   * @returns Promise resolved to a datastore object.
   */
  read(id: String|null, rev: String|null): Promise<any>|null;

  /**
   * Computes past mindnight for given timestamp.
   *
   * @param time Timestamp
   * @returns Time reduced to midnight.
   */
  _computeMidnight(time: Number|null): Number|null;

  /**
   * Dispatches non-cancelable change event.
   *
   * @param type Event type
   * @param detail A detail object to dispatch.
   * @returns Created and dispatched event.
   */
  _fireUpdated(type: String|null, detail: object|null): CustomEvent|null;

  /**
   * Handles any exception in the model in a unified way.
   *
   * @param e An error object
   * @param noThrow If set the function will not throw error.
   * This allow to do the logic without stopping program.
   */
  _handleException(e: Error|object|null, noThrow: Boolean|null): void;

  /**
   * Deletes current database.
   */
  deleteModel(): Promise<any>|null;

  /**
   * Handler for `destroy-model` custom event.
   * Deletes current data when scheduled for deletion.
   */
  _deleteModelHandler(e: CustomEvent|null): void;
  _eventCancelled(e: any): any;
  _cancelEvent(e: any): void;
}
