/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   host-rules-model.html
 */

/// <reference path="base-model.d.ts" />

declare namespace LogicElements {

  /**
   * Model for host rules.
   */
  class HostRulesModel extends Polymer.Element {

    /**
     *  A handler to host rules database
     */
    readonly db: any;
    _attachListeners(node: any): void;
    _detachListeners(node: any): void;

    /**
     * Updates / saves the host rule object in the datastore.
     * This function fires `host-rules-changed` event.
     *
     * @param rule A rule object to save / update
     * @returns Resolved promise to updated object with updated `_rev`
     */
    update(rule: object|null): Promise<any>|null;

    /**
     * Removed an object from the datastore.
     * This function fires `host-rules-deleted` event.
     *
     * @param id The ID of the datastore entry.
     * @param rev Specific revision to read. Defaults to latest revision.
     * @returns Promise resolved to a new `_rev` property of deleted object.
     */
    remove(id: String|null, rev: String|null): Promise<any>|null;

    /**
     * Lists all existing host rules
     *
     * @returns Promise resolved to list of the host rules
     */
    list(): Promise<any>|null;
    _updatedHandler(e: any): void;
    _deletedHandler(e: any): void;
    _listHandler(e: any): void;
  }
}

interface HTMLElementTagNameMap {
  "host-rules-model": LogicElements.HostRulesModel;
}
