/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   workers/index-build.js
 */

/**
 * A web worker class responsible for indexing a datastore
 */
declare class ArcIndexer {

  /**
   * Creates the name for the data store that contains full text items.
   *
   * @param name Name of the store to use for particular index.
   */
  _createTextSearchStoreName(name: String|null): String|null;

  /**
   * Opens a connection to a data store.
   */
  _openSearchStore(name: String|null): Promise<any>|null;

  /**
   * Indexes the data store in a batch operation.
   */
  index(): Promise<any>|null;

  /**
   * Recursively creates an index.
   */
  _indexRecursive(): void;

  /**
   * Normalizes text and replaces national accents with latin letters.
   */
  _normalizeText(str: String|null): String|null;

  /**
   * Creates an indexed documents to be stored in the data store.
   *
   * @param value Text value to process
   * @param documentId Original document id.
   * @returns List of documents to store.
   */
  createTextIndexDocuments(value: String|null, documentId: String|null): Array<object|null>|null|undefined;

  /**
   * Creates an index from a text.
   *
   * @param db Handler to the database
   * @param value Text value to process
   * @param documentId Original document id.
   */
  createTextIndex(db: object|null, value: String|null, documentId: String|null): Promise<any>|null;

  /**
   * Stores =generated index in the data store.
   *
   * @param db [description]
   * @param index [description]
   * @returns [description]
   */
  _storeIndex(db: any, index: any): any;

  /**
   * Creates searchable document.
   *
   * @param value [description]
   * @param docId [description]
   * @returns [description]
   */
  _createIndexDoc(value: any, docId: any): any;

  /**
   * Indexes incomming data.
   *
   * @param data PouchDB data list
   */
  _processResponse(data: Array<object|null>|null): Promise<any>|null;

  /**
   * Removes previously indexed values.
   *
   * @param db Handler for thr IDB
   * @param key Document id
   */
  _clearIndex(db: object|null, key: String|null): Promise<any>|null;
}
