/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   workers/request-db.js
 *   workers/request-db.js
 *   workers/request-db.js
 *   workers/request-db.js
 *   workers/request-db.js
 */

/**
 * A databse helper for requests indexing.
 */
declare class RequestDb {

  /**
   * Opens search index data store.
   */
  openSearchStore(): Promise<any>|null;

  /**
   * Creates a database schema when is newly created.
   *
   * @param e Database create request event
   */
  createSchema(e: Event|null): void;

  /**
   * Generates UUID
   */
  uuid(): String|null;
}

/**
 * A databse helper for requests indexing.
 */
declare class RequestDb {

  /**
   * Opens search index data store.
   */
  openSearchStore(): Promise<any>|null;

  /**
   * Creates a database schema when is newly created.
   *
   * @param e Database create request event
   */
  createSchema(e: Event|null): void;

  /**
   * Generates UUID
   */
  uuid(): String|null;
}

/**
 * A databse helper for requests indexing.
 */
declare class RequestDb {

  /**
   * Opens search index data store.
   */
  openSearchStore(): Promise<any>|null;

  /**
   * Creates a database schema when is newly created.
   *
   * @param e Database create request event
   */
  createSchema(e: Event|null): void;

  /**
   * Generates UUID
   */
  uuid(): String|null;
}

/**
 * A databse helper for requests indexing.
 */
declare class RequestDb {

  /**
   * Opens search index data store.
   */
  openSearchStore(): Promise<any>|null;

  /**
   * Creates a database schema when is newly created.
   *
   * @param e Database create request event
   */
  createSchema(e: Event|null): void;

  /**
   * Generates UUID
   */
  uuid(): String|null;
}

/**
 * A databse helper for requests indexing.
 */
declare class RequestDb {

  /**
   * Opens search index data store.
   */
  openSearchStore(): Promise<any>|null;

  /**
   * Creates a database schema when is newly created.
   *
   * @param e Database create request event
   */
  createSchema(e: Event|null): void;

  /**
   * Generates UUID
   */
  uuid(): String|null;
}
